before:
  hooks:
builds:
  - id: "linux"
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm
      - arm64
      - mipsle
    goos:
      - linux
    goarm:
      - 6
      - 7
    gomips:
      - softfloat
  - id: "non-linux"
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - windows
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    files:
      - example.yaml
      - systemd/hover-ddns.service
nfpms:
  - builds:
      - "linux"
    replacements:
      amd64: x86_64
      linux: Linux
    homepage: https://github.com/dschanoeh/hover-ddns
    maintainer: Jan-Niklas Meier <jan@jansblog.org>
    description: A Dynamic DNS client for the unofficial Hover API.
    license: Apache 2.0
    bindir: /usr/bin
    formats:
      - deb
    contents:
      - src: example.yaml
        dst: /etc/hover-ddns.yaml
        type: config
      - src: systemd/hover-ddns-packaged.service
        dst: /lib/systemd/system/hover-ddns.service
    scripts:
      postinstall: scripts/postinstall.sh
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  github:
    owner: dschanoeh
    name: hover-ddns
dockers:
  - image_templates:
      - "dschanoeh/{{ .ProjectName }}:{{ .Version }}-amd64"
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
  - image_templates:
      - "dschanoeh/{{ .ProjectName }}:{{ .Version }}-arm64"
    use: buildx
    goarch: arm64
    build_flag_templates:
      - --platform=linux/arm64/v8
docker_manifests:
  - name_template: 'dschanoeh/{{ .ProjectName }}:{{ .Version }}'
    image_templates:
      - 'dschanoeh/{{ .ProjectName }}:{{ .Version }}-amd64'
      - 'dschanoeh/{{ .ProjectName }}:{{ .Version }}-arm64'
  - name_template: 'dschanoeh/{{ .ProjectName }}:latest'
    image_templates:
      - 'dschanoeh/{{ .ProjectName }}:{{ .Version }}-amd64'
      - 'dschanoeh/{{ .ProjectName }}:{{ .Version }}-arm64'
